apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: node:18
          command: ["node", "dist/main.js"]
          ports:
            - containerPort: 3000
